# Introdução a Análise de Dados

### Como funciona um Projeto de Análise de Dados?

Os projetos de Análise de Dados são na verdade Desafios das Empresas

### Desafio

- Empresa Vende Bermudas
- 5 Lojas
- Está querendo aumentar as vendas
- O que fazer?
- Informações Disponíveis: Base de Vendas

### Passo 1 - Trazer sua base de dados para o Python e ver o que tem nela

In [8]:
import pandas as pd

tabela = pd.read_excel('Vendas.xlsx', sheet_name='Plan1')
print(tabela.shape)
display(tabela.head())

(57, 6)

        Data             ID Loja           Produto  Quantidade  Valor Unitário  Valor Final
0 2019-12-01   Iguatemi Campinas   Bermuda Estampa           1             169          169
1 2019-12-01  Iguatemi Esplanada    Bermuda Xadrez           1             155          155
2 2019-12-01      Norte Shopping           Bermuda           2             150          300
3 2019-12-01   Iguatemi Campinas  Bermuda Listrado           3             163          489
4 2019-12-01   Iguatemi Campinas     Bermuda Linho           3             195          585

### Passo 2 - Pegar um panorama geral sobre a sua base de dados

In [23]:
faturamento_total = tabela['Valor Final'].sum()
print(faturamento_total)

print()

55895

ID Loja
Iguatemi Campinas             41720
Bourbon Shopping SP            4386
Norte Shopping                 4322
Center Shopping Uberlândia     2994
Iguatemi Esplanada             2473
Name: Valor Final, dtype: int64

ID Loja
Iguatemi Campinas             264
Bourbon Shopping SP            27
Norte Shopping                 27
Center Shopping Uberlândia     18
Iguatemi Esplanada             14
Name: Quantidade, dtype: int64

ID Loja
Bourbon Shopping SP           195
Center Shopping Uberlândia    195
Iguatemi Campinas             195
Iguatemi Esplanada            195
Norte Shopping                195
Name: Valor Unitário, dtype: int64

### Passo 3 - Começar sua análise Top -> Down

In [24]:
faturamento_total_empresa = tabela.groupby('ID Loja')['Valor Final'].sum()
print(faturamento_total_empresa.sort_values(ascending = False))

print()

quantidade_produtos_total_empresa = tabela.groupby('ID Loja')['Quantidade'].sum().sort_values(ascending = False)
print(quantidade_produtos_total_empresa)

print()

preco_max_loja =  tabela.groupby('ID Loja')['Valor Unitário'].max()
print(preco_max_loja)

ID Loja
Iguatemi Campinas             41720
Bourbon Shopping SP            4386
Norte Shopping                 4322
Center Shopping Uberlândia     2994
Iguatemi Esplanada             2473
Name: Valor Final, dtype: int64

ID Loja
Iguatemi Campinas             264
Bourbon Shopping SP            27
Norte Shopping                 27
Center Shopping Uberlândia     18
Iguatemi Esplanada             14
Name: Quantidade, dtype: int64

ID Loja
Bourbon Shopping SP           195
Center Shopping Uberlândia    195
Iguatemi Campinas             195
Iguatemi Esplanada            195
Norte Shopping                195
Name: Valor Unitário, dtype: int64

### Passo 4 - Entrar no detalhe pra entender

In [34]:
faturamento_por_produto = tabela[['ID Loja','Produto','Valor Final']].groupby(['ID Loja','Produto']).sum()#.sort_values( ascending = False)
display(faturamento_por_produto);

                                             Valor Final
ID Loja                    Produto
Bourbon Shopping SP        Bermuda                   750
                           Bermuda Estampa          1183
                           Bermuda Linho             195
                           Bermuda Listrado         1793
                           Bermuda Xadrez            465
Center Shopping Uberlândia Bermuda Estampa           338
                           Bermuda Linho             780
                           Bermuda Listrado          326
                           Bermuda Xadrez           1550
Iguatemi Campinas          Bermuda                  1200
                           Bermuda Estampa           845
                           Bermuda Linho            1170
                           Bermuda Liso            36581
                           Bermuda Listrado         1304
                           Bermuda Xadrez            620
Iguatemi Esplanada         Bermuda                   150
                           Bermuda Estampa           338
                           Bermuda Linho            1365
                           Bermuda Xadrez            620
Norte Shopping             Bermuda                  1350
                           Bermuda Estampa           845
                           Bermuda Linho             390
                           Bermuda Listrado          652
                           Bermuda Xadrez           1085